AI_quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("accounts.urls")),
        path("", include("main.urls")),
        path("", include("shop.urls")),
        path("", include("game.urls")),
        path("", include("multiplayer.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

accounts/urls.py
from django.urls import path
from .views import *


urlpatterns = [
     path("users/<slug:username>/",UserDetailView.as_view(),name="user_details"),
     path("login/", UserLoginView.as_view(), name="login_view"),
     path("logout/",UserLogoutView.as_view(),name="logout_view"),
     path("register/", UserRegisterView.as_view(), name="register_view"),
     path("users/<slug:username>/update/",UserUpdateView.as_view(),name="user_update"),
     path('leaderboard/', LeaderboardListView.as_view(), name='leaderboard'),
     path('leaderboard-swap/', leaderboard_swap, name='leaderboard_swap'),
     path('login-swap/', login_swap, name='login_swap'),
     path('users-swap/', userdetail_swap, name='profile_swap'),
     path('userupdate-swap/', userupdate_swap, name='userupdate_swap'),
     path("register-swap/", register_swap, name="register_swap")
 ]

game/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("game/", game_view, name="game_view"),
    path("game-start", game_start, name="game_start"),
    path("start-result", start_result, name="start_result"),
    #path('game-over', game_over, "game_over"),
    path("game-settings-swap/", game_settings_swap, name="game_settings_swap"),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image

class CustomUser(AbstractUser):
    NATION_CHOICES = [
        ('AF', 'Afghanistan'),
        ('AL', 'Albania'),
        ('DZ', 'Algeria'),
        ('AS', 'American Samoa'),
        ('AD', 'Andorra'),
        ('AO', 'Angola'),
        ('AI', 'Anguilla'),
        ('AQ', 'Antarctica'),
        ('AG', 'Antigua and Barbuda'),
        ('AR', 'Argentina'),
        ('AM', 'Armenia'),
        ('AW', 'Aruba'),
        ('AU', 'Australia'),
        ('AT', 'Austria'),
        ('AZ', 'Azerbaijan'),
        ('BS', 'Bahamas'),
        ('BH', 'Bahrain'),
        ('BD', 'Bangladesh'),
        ('BB', 'Barbados'),
        ('BY', 'Belarus'),
        ('BE', 'Belgium'),
        ('BZ', 'Belize'),
        ('BJ', 'Benin'),
        ('BM', 'Bermuda'),
        ('BT', 'Bhutan'),
        ('BO', 'Bolivia'),
        ('BA', 'Bosnia and Herzegovina'),
        ('BW', 'Botswana'),
        ('BR', 'Brazil'),
        ('IO', 'British Indian Ocean Territory'),
        ('VG', 'British Virgin Islands'),
        ('BN', 'Brunei'),
        ('BG', 'Bulgaria'),
        ('BF', 'Burkina Faso'),
        ('BI', 'Burundi'),
        ('KH', 'Cambodia'),
        ('CM', 'Cameroon'),
        ('CA', 'Canada'),
        ('CV', 'Cape Verde'),
        ('KY', 'Cayman Islands'),
        ('CF', 'Central African Republic'),
        ('TD', 'Chad'),
        ('CL', 'Chile'),
        ('CN', 'China'),
        ('CX', 'Christmas Island'),
        ('CC', 'Cocos (Keeling) Islands'),
        ('CO', 'Colombia'),
        ('KM', 'Comoros'),
        ('CG', 'Congo'),
        ('CD', 'Congo (Democratic Republic of the)'),
        ('CK', 'Cook Islands'),
        ('CR', 'Costa Rica'),
        ('CI', 'Ivory Coast'),
        ('HR', 'Croatia'),
        ('CU', 'Cuba'),
        ('CY', 'Cyprus'),
        ('CZ', 'Czech Republic'),
        ('DK', 'Denmark'),
        ('DJ', 'Djibouti'),
        ('DM', 'Dominica'),
        ('DO', 'Dominican Republic'),
        ('EC', 'Ecuador'),
        ('EG', 'Egypt'),
        ('SV', 'El Salvador'),
        ('GQ', 'Equatorial Guinea'),
        ('ER', 'Eritrea'),
        ('EE', 'Estonia'),
        ('ET', 'Ethiopia'),
        ('FK', 'Falkland Islands'),
        ('FO', 'Faroe Islands'),
        ('FJ', 'Fiji'),
        ('FI', 'Finland'),
        ('FR', 'France'),
        ('GF', 'French Guiana'),
        ('PF', 'French Polynesia'),
        ('TF', 'French Southern Territories'),
        ('GA', 'Gabon'),
        ('GM', 'Gambia'),
        ('GE', 'Georgia'),
        ('DE', 'Germany'),
        ('GH', 'Ghana'),
        ('GI', 'Gibraltar'),
        ('GR', 'Greece'),
        ('GL', 'Greenland'),
        ('GD', 'Grenada'),
        ('GP', 'Guadeloupe'),
        ('GU', 'Guam'),
        ('GT', 'Guatemala'),
        ('GG', 'Guernsey'),
        ('GN', 'Guinea'),
        ('GW', 'Guinea-Bissau'),
        ('GY', 'Guyana'),
        ('HT', 'Haiti'),
        ('HN', 'Honduras'),
        ('HK', 'Hong Kong'),
        ('HU', 'Hungary'),
        ('IS', 'Iceland'),
        ('IN', 'India'),
        ('ID', 'Indonesia'),
        ('IR', 'Iran'),
        ('IQ', 'Iraq'),
        ('IE', 'Ireland'),
        ('IL', 'Israel'),
        ('IT', 'Italy'),
        ('JM', 'Jamaica'),
        ('JP', 'Japan'),
        ('JE', 'Jersey'),
        ('JO', 'Jordan'),
        ('KZ', 'Kazakhstan'),
        ('KE', 'Kenya'),
        ('KI', 'Kiribati'),
        ('KW', 'Kuwait'),
        ('KG', 'Kyrgyzstan'),
        ('LA', 'Laos'),
        ('LV', 'Latvia'),
        ('LB', 'Lebanon'),
        ('LS', 'Lesotho'),
        ('LR', 'Liberia'),
        ('LY', 'Libya'),
        ('LI', 'Liechtenstein'),
        ('LT', 'Lithuania'),
        ('LU', 'Luxembourg'),
        ('MO', 'Macau'),
        ('MK', 'Macedonia'),
        ('MG', 'Madagascar'),
        ('MW', 'Malawi'),
        ('MY', 'Malaysia'),
        ('MV', 'Maldives'),
        ('ML', 'Mali'),
        ('MT', 'Malta'),
        ('MH', 'Marshall Islands'),
        ('MQ', 'Martinique'),
        ('MR', 'Mauritania'),
        ('MU', 'Mauritius'),
        ('YT', 'Mayotte'),
        ('MX', 'Mexico'),
        ('FM', 'Micronesia'),
        ('MD', 'Moldova'),
        ('MC', 'Monaco'),
        ('MN', 'Mongolia'),
        ('ME', 'Montenegro'),
        ('MS', 'Montserrat'),
        ('MA', 'Morocco'),
        ('MZ', 'Mozambique'),
        ('MM', 'Myanmar'),
        ('NA', 'Namibia'),
        ('NR', 'Nauru'),
        ('NP', 'Nepal'),
        ('NL', 'Netherlands'),
        ('NC', 'New Caledonia'),
        ('NZ', 'New Zealand'),
        ('NI', 'Nicaragua'),
        ('NE', 'Niger'),
        ('NG', 'Nigeria'),
        ('NU', 'Niue'),
        ('NF', 'Norfolk Island'),
        ('KP', 'North Korea'),
        ('NO', 'Norway'),
        ('OM', 'Oman'),
        ('PK', 'Pakistan'),
        ('PW', 'Palau'),
        ('PA', 'Panama'),
        ('PG', 'Papua New Guinea'),
        ('PY', 'Paraguay'),
        ('PE', 'Peru'),
        ('PH', 'Philippines'),
        ('PN', 'Pitcairn Islands'),
        ('PL', 'Poland'),
        ('PT', 'Portugal'),
        ('PR', 'Puerto Rico'),
        ('QA', 'Qatar'),
        ('RE', 'Réunion'),
        ('RO', 'Romania'),
        ('RU', 'Russia'),
        ('RW', 'Rwanda'),
        ('BL', 'Saint Barthélemy'),
        ('SH', 'Saint Helena'),
        ('KN', 'Saint Kitts and Nevis'),
        ('LC', 'Saint Lucia'),
        ('MF', 'Saint Martin'),
        ('SX', 'Sint Maarten'),
        ('PM', 'Saint Pierre and Miquelon'),
        ('VC', 'Saint Vincent and the Grenadines'),
        ('WS', 'Samoa'),
        ('SM', 'San Marino'),
        ('ST', 'São Tomé and Príncipe'),
        ('SA', 'Saudi Arabia'),
        ('SN', 'Senegal'),
        ('RS', 'Serbia'),
        ('SC', 'Seychelles'),
        ('SL', 'Sierra Leone'),
        ('SG', 'Singapore'),
        ('SK', 'Slovakia'),
        ('SI', 'Slovenia'),
        ('SB', 'Solomon Islands'),
        ('SO', 'Somalia'),
        ('ZA', 'South Africa'),
        ('KR', 'South Korea'),
        ('SS', 'South Sudan'),
        ('ES', 'Spain'),
        ('LK', 'Sri Lanka'),
        ('SD', 'Sudan'),
        ('SR', 'Suriname'),
        ('SJ', 'Svalbard and Jan Mayen'),
        ('SZ', 'Swaziland'),
        ('SE', 'Sweden'),
        ('CH', 'Switzerland'),
        ('SY', 'Syria'),
        ('TW', 'Taiwan'),
        ('TJ', 'Tajikistan'),
        ('TZ', 'Tanzania'),
        ('TH', 'Thailand'),
        ('TG', 'Togo'),
        ('TK', 'Tokelau'),
        ('TO', 'Tonga'),
        ('TT', 'Trinidad and Tobago'),
        ('TN', 'Tunisia'),
        ('TR', 'Turkey'),
        ('TM', 'Turkmenistan'),
        ('TC', 'Turks and Caicos Islands'),
        ('TV', 'Tuvalu'),
        ('UG', 'Uganda'),
        ('UA', 'Ukraine'),
        ('AE', 'United Arab Emirates'),
        ('GB', 'United Kingdom'),
        ('US', 'United States'),
        ('UY', 'Uruguay'),
        ('UZ', 'Uzbekistan'),
        ('VU', 'Vanuatu'),
    ]

    image = models.ImageField(upload_to="user_profile_images/", default="user_profile_images/profile_placeholder.jpeg")
    stars = models.IntegerField(default=0)
    coins = models.IntegerField(default=0)
    nation = models.CharField(max_length=2, choices=NATION_CHOICES, default='DE')
    average_stars_per_game = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    games_played = models.IntegerField(default=0) 

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 300 or img.width > 300:
                img = img.resize((300, 300))
                img.save(self.image.path)

    def __str__(self):
        return self.username

accounts/views.py
from django.shortcuts import render, redirect
from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, logout
from .form import CustomUserCreationForm, UserUpdateForm
from django.views.generic import (
    ListView,
    CreateView,
    FormView,
    RedirectView,
    View,
    DetailView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect




class UserLoginView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = reverse_lazy("home_view")

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        print(self.request)
        return super().form_valid(form)


class UserLogoutView(RedirectView):
    url = reverse_lazy("home_view")

    def get(self, request, *args, **kwargs):
        logout(request)
        print(self.request.user)
        return super().get(request, *args, **kwargs)


class UserRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("home_view")


class UserDetailView(DetailView):
    model = CustomUser
    template_name = "profile.html"
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = UserUpdateForm
    template_name = "profile_update.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    success_url = reverse_lazy("home_view")

    def get_object(self):
        return self.request.user


class LeaderboardListView(ListView):
    model = CustomUser
    template_name = "leaderboard.html"
    context_object_name = "users"
    queryset = CustomUser.objects.all().order_by("-stars")


# Views for partials (fetched and swapped into <main> in basic.html
# to not reload the entire page)


def leaderboard_swap(request):
    users = CustomUser.objects.all().order_by("-stars")
    return render(
        request,
        template_name="leaderboard_swap.html",
        context={"users": users},
    )

def login_swap(request):
    if request.method == "GET":
        # Just render the partial with an empty form
        form = AuthenticationForm()
        return render(request, 'login_swap.html', {'form': form})

    elif request.method == "POST":
        # Attempt to authenticate & login
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # Instruct the browser to do a full redirect:
            response = HttpResponse(status=200)
            response['HX-Redirect'] = reverse('user_details', args=[user.username])
            return response
        # If form is not valid, re-render partial with errors:
        return render(request, 'login_swap.html', {'form': form})


def userdetail_swap(request):
    user = request.user
    return render(request, 'profile_swap.html', {'user': user})

@login_required
def userupdate_swap(request):
    user = request.user 
    
    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect(reverse("home_view")) 
    else:
        form = UserUpdateForm(instance=user)

    return render(request, "profile_update_swap.html", {"form": form})

def register_swap(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # Benutzer speichern
            login(request, user)  # Direkt einloggen nach der Registrierung
            return redirect(reverse("home_view"))  # Weiterleitung nach Registrierung
    else:
        form = CustomUserCreationForm()

    return render(request, "register_swap.html", {"form": form})

accounts/templates/leaderboard.html
{% extends 'base.html' %}
{% block title %}The AI-Quiz - Leaderboard{% endblock %}
{% block content %}
<div class="base-container leaderboard">
    
    <div class="content-container-shadow leaderboard">
        <h1>Leaderboard</h1>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Nation</th>
                    <th>Total Games</th>
                    <th id="stars-header" style="cursor: pointer;" title="Click to switch">
                        Stars / <span class="inactive">Avg. Stars</span>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'user_details' username=user.username %}" class="profile-link">
                                {{ user.username }}
                            </a>
                        </td>
                        <td>
                            <div class="nation-container">
                                <img src="https://flagicons.lipis.dev/flags/4x3/{{ user.nation|lower }}.svg" alt="{{ user.nation }}" class="flag-icon">
                                <span class="nation-name">{{ user.nation|upper }}</span>
                            </div>
                        </td>
                        <td style="font-weight: bold;">{{ user.games_played }}</td>
                        <td data-original-stars="{{ user.stars }}" data-average-stars="{{ user.average_stars_per_game }}" style="font-weight: bold;">
                            {{ user.stars }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

accounts/templates/leaderboard_partial.html
<div class="base-container leaderboard">
    <div class="leaderboard-container">
        <h1>Leaderboard</h1>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Nation</th>
                    <th id="stars-header" style="cursor: pointer;" title="Click to switch">Stars</th>
 
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'user_details' username=user.username %}" class="profile-link">{{ user.username }}</a></td>
                        <td>
                            <div class="nation-container">
                                <img src="https://flagicons.lipis.dev/flags/4x3/{{ user.nation|lower }}.svg" alt="{{ user.nation }}" class="flag-icon">
                                <span class="nation-name">{{ user.nation|upper }}</span> 
                            </div>
                        </td>
                        <td data-original-stars="{{ user.stars }}" data-average-stars="{{ user.average_stars_per_game }}"style="font-weight: bold;">
                            {{ user.stars }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

accounts/templates/leaderboard_swap.html
<div class="base-container leaderboard">
    
    <div class="content-container-shadow leaderboard">
        <h1>Leaderboard</h1>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Nation</th>
                    <th>Total Games</th>
                    <th id="stars-header" style="cursor: pointer;" title="Click to switch">
                        Stars / <span class="inactive">Avg. Stars</span>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'user_details' username=user.username %}" class="profile-link">
                                {{ user.username }}
                            </a>
                        </td>
                        <td>
                            <div class="nation-container">
                                <img src="https://flagicons.lipis.dev/flags/4x3/{{ user.nation|lower }}.svg" alt="{{ user.nation }}" class="flag-icon">
                                <span class="nation-name">{{ user.nation|upper }}</span> 
                            </div>
                        </td>
                        <td style="font-weight: bold;">{{ user.games_played }}</td>
                        <td data-original-stars="{{ user.stars }}" data-average-stars="{{ user.average_stars_per_game }}" style="font-weight: bold;">
                            {{ user.stars }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

accounts/templates/profile.html
{% extends 'base.html' %} {% load static %} {% block title %} The AI-Quiz -
Profile {% endblock %} {% block content %}

<div class="base-container">
  <div class="content-container-shadow profile">
    <h1>{{ user.username }}'s Profile</h1>
    {% if user.first_name %}
    <h3><span>Name: </span> {{ user.first_name }}</h3>
    {% endif %}
    <h4><span>Stars: </span> {{ user.stars }}</h4>
    <!-- Always show Stars -->
    <h4>
      <span>Average Stars Per Game: </span> {{ user.average_stars_per_game }}
    </h4>
    <!-- Always show Average Stars per Game -->
    <h4><span>Nation: </span> {{ user.get_nation_display }}</h4>
    <!-- Always show Nation -->

    {% if user.is_authenticated %} {% if user == request.user %}
    <h4><span>Email: </span> {{ user.email }}</h3>
    <!-- Show Email only if logged in and it's their own profile -->
    <h4><span>Coins: </span> {{ user.coins }}</h4>
    <!-- Show Coins only if logged in and it's their own profile -->
    <a 
      class="update-button" 
      href="{% url 'user_update' user.username %}"
      hx-get="{% url 'userupdate_swap'%}"
      hx-target="#content-area"
      hx-swap="innerHTML"
      hx-push-url="{% url 'user_update' user.username %}"
      >Update Profile</a
    >
    <!-- Show Update Profile button only for own profile -->
    {% endif %} {% endif %}
    <div>
      <img
        src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'assets/profile_placeholder.jpeg' %}{% endif %}"
        alt="Profile image"
        width="300"
        height="300"
      />
    </div>
  </div>


</div>

{% endblock %}

accounts/templates/profile_swap.html
<div class="base-container">
  <div class="content-container-shadow profile">
    <h1>{{ user.username }}'s Profile</h1>
    {% if user.first_name %}
    <h3><span>Name: </span> {{ user.first_name }}</h3>
    {% endif %}
    <h4><span>Stars: </span> {{ user.stars }}</h4>
    <!-- Always show Stars -->
    <h4>
      <span>Average Stars Per Game: </span> {{ user.average_stars_per_game }}
    </h4>
    <!-- Always show Average Stars per Game -->
    <h4><span>Nation: </span> {{ user.get_nation_display }}</h4>
    <!-- Always show Nation -->

    {% if user.is_authenticated %} {% if user == request.user %}
    <h4><span>Email: </span> {{ user.email }}</h4>
    <!-- Show Email only if logged in and it's their own profile -->
    <h4><span>Coins: </span> {{ user.coins }}</h4>
    <!-- Show Coins only if logged in and it's their own profile -->
    <a 
      class="update-button" 
      href="{% url 'user_update' user.username %}"
      hx-get="{% url 'userupdate_swap'%}"
      hx-target="#content-area"
      hx-swap="innerHTML"
      hx-push-url="{% url 'user_update' user.username %}"
      >Update Profile</a
    >
    <!-- Show Update Profile button only for own profile -->
    {% endif %} {% endif %}
    <div>
     {% if user.image %}
      <img src="{{ user.image.url }}" alt="User Image" />
      {% endif %}
    </div>
  </div>
</div>

accounts/templates/register.html
{% extends 'base.html' %}
{% block title %} The AI-Quiz - Register {% endblock %}
{% block content %}
<div class="register-container">
  <div class="register-form">
    <h2>Register</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="form-group-register">
        <label for="id_username">Username:</label>
        <input 
          type="text" 
          name="username" 
          id="id_username" 
          required 
        />
        {% if form.username.errors %}
          <div class="error">{{ form.username.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_email">Email:</label>
        <input 
          type="email" 
          name="email" 
          id="id_email" 
          required
        />
        {% if form.email.errors %}
          <div class="error">{{ form.email.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_nation">Nation:</label>
        <select 
          name="nation" 
          id="id_nation"
        >
          {% for value, label in form.nation.field.choices %}
            <option value="{{ value }}" {% if form.nation.value == value %}selected{% endif %}>
              {{ label }}
            </option>
          {% endfor %}
        </select>
        {% if form.nation.errors %}
          <div class="error">{{ form.nation.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_image">Upload New Profile Image:</label>
        <input 
          type="file" 
          name="image" 
          id="id_image" 
          placeholder="--Choose Image--"
        />
        {% if form.image.errors %}
          <div class="error">{{ form.image.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_password">New Password:</label>
        <input 
          type="password" 
          name="password1" 
          id="id_password" 
          required
        />
        {% if form.password.errors %}
          <div class="error">{{ form.password.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_password_repeat">Repeat New Password:</label>
        <input 
          type="password" 
          name="password2" 
          id="id_password_repeat" 
          required
        />
        {% if form.password_repeat.errors %}
          <div class="error">{{ form.password_repeat.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <input
          class="w3-check"
          type="checkbox"
          id="toggle-input"
          onclick="PasswordVisibility()"
        />
        <label for="toggle-input">Show Password</label>
      </div>
      
      <div class="form-group button-group">
        <button type="submit">REGISTER</button>
        <a href="{% url 'login_view' %}" class="cancel-button"
          hx-get="{% url 'login_swap' %}"
          hx-target="#content-area"
          hx-swap="innerHTML"
          hx-push-url="{% url 'login_view' %}">
          CANCEL
        </a>
      </div>
      
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/register_swap.html
<div class="register-container">
  <div class="register-form">
    <h2>Register</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="form-group-register">
        <label for="id_username">Username:</label>
        <input 
          type="text" 
          name="username" 
          id="id_username" 
          required
        />
        {% if form.username.errors %}
          <div class="error">{{ form.username.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_email">Email:</label>
        <input 
          type="email" 
          name="email" 
          id="id_email"
        />
        {% if form.email.errors %}
          <div class="error">{{ form.email.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_nation">Nation:</label>
        <select 
          name="nation" 
          id="id_nation"
        >
          {% for value, label in form.nation.field.choices %}
            <option value="{{ value }}" {% if form.nation.value == value %}selected{% endif %}>
              {{ label }}
            </option>
          {% endfor %}
        </select>
        {% if form.nation.errors %}
          <div class="error">{{ form.nation.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_image">Upload New Profile Image:</label>
        <input 
          type="file" 
          name="image" 
          id="id_image" 
          placeholder="--Choose Image--"
        />
        {% if form.image.errors %}
          <div class="error">{{ form.image.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_password">New Password:</label>
        <input 
          type="password" 
          name="password1" 
          id="id_password" 
        />
        {% if form.password.errors %}
          <div class="error">{{ form.password.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <label for="id_password_repeat">Repeat New Password:</label>
        <input 
          type="password" 
          name="password2" 
          id="id_password_repeat" 
        />
        {% if form.password_repeat.errors %}
          <div class="error">{{ form.password_repeat.errors }}</div>
        {% endif %}
      </div>
      
      <div class="form-group-register">
        <input
          class="w3-check"
          type="checkbox"
          id="toggle-input"
          onclick="PasswordVisibility()"
        />
        <label for="toggle-input">Show Password</label>
      </div>
      
      <div class="button-group">
        <button type="submit">REGISTER</button>
        <a href="{% url 'login_view' %}" class="cancel-button"
          hx-get="{% url 'login_swap' %}"
          hx-target="#content-area"
          hx-swap="innerHTML"
          hx-push-url="{% url 'login_view' %}">
          CANCEL
        </a>
      </div>
    </form>
  </div>
</div>

accounts/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>